# Generated by Django 4.0.2 on 2022-02-06 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='b_day',
            field=models.DateField(default=datetime.date(2022, 2, 6), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tagsString',
            field=models.CharField(max_length=300),
        ),
    ]
