# Generated by Django 4.0.1 on 2022-01-28 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='b_day',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 13, 24, 8, 434397, tzinfo=utc), null=True),
        ),
    ]
