# Generated by Django 4.0 on 2022-02-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('helper_app', '0002_rename_note_path_notes_note_disc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_tag', models.CharField(default='just note', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.DeleteModel(
            name='NoteTags',
        ),
        migrations.AddField(
            model_name='notestag',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='tags_list', to='helper_app.Note'),
        ),
    ]
