# Generated by Django 4.0.1 on 2022-01-28 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_alter_contacts_b_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='b_day',
            field=models.DateField(default=datetime.date(2022, 1, 28), null=True),
        ),
    ]
