# Generated by Django 4.0 on 2022-02-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0003_notestag_rename_notes_note_delete_notetags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_disc',
            new_name='note_desc',
        ),
    ]
