# Generated by Django 4.0 on 2022-02-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0005_note_tag_delete_notestag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.AddField(
            model_name='note',
            name='tag_list',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.CreateModel(
            name='NotesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_tag', models.CharField(default='just note', max_length=20)),
                ('notes', models.ManyToManyField(blank=True, related_name='tags_list', to='helper_app.Note')),
            ],
        ),
    ]
