# Generated by Django 4.0 on 2022-02-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0008_rename_tag_list_note_tags_delete_notestag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_name',
            new_name='title',
        ),
    ]
