# Generated by Django 4.0 on 2022-02-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0009_rename_note_desc_note_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='tagInput',
        ),
    ]
