# Generated by Django 4.0 on 2022-02-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0010_rename_tags_note_taginput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tagInput',
            new_name='tags',
        ),
    ]
