# Generated by Django 4.0 on 2022-02-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0011_rename_taginput_note_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='tagString',
        ),
    ]
