# Generated by Django 4.0 on 2022-02-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0012_rename_tags_note_tagstring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tagString',
            new_name='tagsString',
        ),
    ]
