# Generated by Django 4.0.2 on 2022-02-02 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0013_rename_tagstring_note_tagsstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='b_day',
            field=models.DateField(default=datetime.date(2022, 2, 2), null=True),
        ),
    ]
