# Generated by Django 4.0 on 2022-02-03 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0014_alter_contacts_b_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='b_day',
            field=models.DateField(default=datetime.date(2022, 2, 3), null=True),
        ),
    ]
